import { fonts } from "@/configs/font";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Foso Test by Thanh Cong Nguyen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fonts.lexendDeca.variable} antialiased`}>{children}</body>
    </html>
  );
}
